const translations = {
  en: {
    login: "Login",
    register: "Register",
    emailOrPhone: "Email or Phone",
    email: "Email",
    phone: "Phone Number",
    password: "Password",
    role: "Role",
    patient: "Patient",
    doctor: "Doctor",
    pharmacist: "Pharmacist",
    admin: "Administrator",
    dashboard: "Dashboard",
    consultation: "Consultation",
    emergency: "Emergency Service",
    prescribe: "Prescribe",
    verify: "Verify Prescription",
    users: "Manage Users",
    reports: "Reports",
    name: "Name",
    age: "Age",
    location: "Location",
    address: "Address",
    symptoms: "Symptoms",
    explanation: "Explanation of Illness",
    submit: "Submit",
    back: "Back",
    logout: "Logout",
    pending: "Pending",
    served: "Served",
    verified: "Verified",
    ambulance: "Ambulance",
    nearestHospital: "Nearest Hospital",
    contact: "Contact",
    scanQR: "Scan QR Code",
    generateQR: "Generate QR Code",
    notification: "Notification",
    success: "Success",
    error: "Error",
    info: "Info",
    fillAllFields: "Please fill all fields",
    requestSent: "Request sent",
    ambulanceRequested: "Ambulance requested",
    yearsOld: "years old",
    viewDetails: "View Details",
    fullDetails: "Full Details",
    patientId: "Patient ID",
    medication: "Medication",
    dosage: "Dosage",
    instructions: "Instructions",
    generateRx: "Generate Rx",
    prescriptionQR: "Prescription QR",
    download: "Download",
    prescriptionDetails: "Prescription Details",
    verifyRx: "Verify Rx",
    cameraError: "Camera error",
    invalidQR: "Invalid QR code",
    validRx: "Valid prescription",
    invalidRx: "Invalid prescription",
    loadUsers: "Load Users",
    delete: "Delete",
    loadReports: "Load Reports",
    consultations: "Consultations",
    emergencies: "Emergencies",
    prescriptions: "Prescriptions",
    emergencyType: "Emergency Type",
    accident: "Accident",
    heartAttack: "Heart Attack",
    stroke: "Stroke",
    other: "Other",
    description: "Description",
    sendEmergency: "Send Emergency",
    healthTips: "Health Education Tips",
    tip1Title: "Stay Hydrated",
    tip1Content: "Drink at least 8 glasses of water daily to maintain good health.",
    tip2Title: "Regular Exercise",
    tip2Content: "Engage in physical activity for at least 30 minutes a day.",
    tip3Title: "Balanced Diet",
    tip3Content: "Eat a variety of fruits, vegetables, and whole grains.",
    tip4Title: "Sleep Well",
    tip4Content: "Aim for 7-9 hours of quality sleep each night.",
    tip5Title: "Hygiene",
    tip5Content: "Wash hands regularly and maintain personal hygiene.",
    noConsultations: "No consultation requests yet.",
    noPrescriptions: "No prescriptions yet.",
    noPharmacies: "No licensed pharmacies found.",
    prescribedNotVerified: "Prescribed but not yet verified by pharmacist",
    verifiedByPharmacist: "Verified by pharmacist",
    pharmacies: "Pharmacies",
    pharmacyFinder: "Pharmacy Finder",
    map: "Map",
    licensed: "Licensed",
    unlicensed: "Unlicensed",
    prescription: "Prescription",
    manualEntry: "Manual Entry",
    prescriptionId: "Prescription ID"
  },
  so: {
    login: "Gal",
    register: "Diiwaangeli",
    emailOrPhone: "Email ama Telefoon",
    email: "Email",
    phone: "Lambarka Telefoonka",
    password: "Furaha",
    role: "Doorka",
    patient: "Bukaanka",
    doctor: "Dhakhtarka",
    pharmacist: "Farmashiistaha",
    admin: "Maamulaha",
    dashboard: "Dashboard-ka",
    consultation: "La-tashi",
    emergency: "Adeegga Degdegga ah",
    prescribe: "Qor",
    verify: "Xaqiiji Qoraalka",
    users: "Maamul Isticmaalayaasha",
    reports: "War-bixinnada",
    name: "Magaca",
    age: "Da'da",
    location: "Goobta",
    address: "Cinwaanka",
    symptoms: "Calamadaha",
    explanation: "Sharaxaada Cudurka",
    submit: "Dir",
    back: "Dib u noqo",
    logout: "Ka bax",
    pending: "Sugaya",
    served: "La adeegay",
    verified: "La xaqiijiyay",
    ambulance: "Ambalaaska",
    nearestHospital: "Isbitaalka ugu dhow",
    contact: "Xiriir",
    scanQR: "Scan QR Code",
    generateQR: "Abuur QR Code",
    notification: "Ogeysiis",
    success: "Guul",
    error: "Khalad",
    info: "Macluumaad",
    fillAllFields: "Fadlan buuxi dhammaan goobaha",
    requestSent: "Codsi la diray",
    ambulanceRequested: "Ambalaas la codsaday",
    yearsOld: "sano jir",
    viewDetails: "Eeg Faahfaahinta",
    fullDetails: "Faahfaahin Buuxda",
    patientId: "Aqoonsiga Bukaanka",
    medication: "Daawada",
    dosage: "Qiyaasta",
    instructions: "Tilmaamaha",
    generateRx: "Abuur Rx",
    prescriptionQR: "QR Qoraalka",
    download: "Soo dejiso",
    prescriptionDetails: "Faahfaahinta Qoraalka",
    verifyRx: "Xaqiiji Rx",
    cameraError: "Khaladka Kamarada",
    invalidQR: "QR Code aan sax ahayn",
    validRx: "Qoraal sax ah",
    invalidRx: "Qoraal aan sax ahayn",
    loadUsers: "Soo rar Isticmaalayaasha",
    delete: "Tirtir",
    loadReports: "Soo rar War-bixinnada",
    consultations: "La-tashiyo",
    emergencies: "Degdegyo",
    prescriptions: "Qoraallo",
    emergencyType: "Nooca Degdegga",
    accident: "Shil",
    heartAttack: "Wadnaxanuun",
    stroke: "Istarook",
    other: "Kale",
    description: "Sharaxaada",
    sendEmergency: "Dir Degdeg",
    healthTips: "Talooyinka Waxbarashada Caafimaadka",
    tip1Title: "Biyo Badan Cab",
    tip1Content: "Cab ugu yaraan 8 koob oo biyo ah maalin kasta si aad u ilaaliso caafimaadka wanaagsan.",
    tip2Title: "Jimicsi Joogto ah",
    tip2Content: "Ku lug yeelo dhaqdhaqaaq jireed ugu yaraan 30 daqiiqo maalintii.",
    tip3Title: "Cunto Dheelitiran",
    tip3Content: "Cun noocyo kala duwan oo khudaar, miraha, iyo badarka.",
    tip4Title: "Hurdo Wanaagsan",
    tip4Content: "Ujeedo 7-9 saacadood oo hurdo tayo leh habeen kasta.",
    tip5Title: "Nadaafadda",
    tip5Content: "Gacmaha si joogto ah u dhaq oo ilaali nadaafadda shakhsi ahaaneed.",
    noConsultations: "Weli lama hayo codsiyo la-talin.",
    noPrescriptions: "Weli qoraal daawo ma jiro.",
    noPharmacies: "Lama helin farmashiyo shati dawli ah.",
    prescribedNotVerified: "Qoraal daawo ayaa la qoray balse wali lama xaqiijin farmashiistaha",
    verifiedByPharmacist: "Waxaa xaqiijiyay farmashiistaha",
    pharmacies: "Farmashiyo",
    pharmacyFinder: "Raadi Farmashiyo",
    map: "Khariidadda",
    licensed: "Leh shati",
    unlicensed: "Aan lahayn shati",
    prescription: "Qoraal",
    manualEntry: "Gacanta ku geli",
    prescriptionId: "Aqoonsiga Qoraalka"
  }
};

// 1. Get saved language OR default to 'en'
let currentLang = localStorage.getItem('lang') || 'en';

// 2. Export functions for use in other JS modules
export function t(key) {
  return translations[currentLang][key] || key;
}

export function updateUI() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = t(key);
  });
}

export function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang); // Save to browser memory
  updateUI();
}

// 3. IMPORTANT: Make it global so HTML buttons can click it
window.setLanguage = setLanguage;

// 4. Run immediately when script loads
updateUI();